const RestaurantsActionsConstants = {
    ADD_RESTAURANT_ACTION: 'ADD_RESTAURANT_ACTION',
    ADD_RESTAURANT_SUCCESS_ACTION: 'ADD_RESTAURANT_SUCCESS_ACTION',
    ADD_RESTAURANT_FAILURE_ACTION: 'ADD_RESTAURANT_FAILURE_ACTION',

    LOAD_RESTAURANTS_ACTION: 'LOAD_RESTAURANTS_ACTION',
    LOAD_RESTAURANTS_SUCCESS_ACTION: 'LOAD_RESTAURANTS_SUCCESS_ACTION',
    LOAD_RESTAURANTS_FAILURE_ACTION: 'LOAD_RESTAURANTS_FAILURE_ACTION',

    LOAD_RESTAURANT_DETAILS_ACTION: 'LOAD_RESTAURANT_DETAILS_ACTION',
    LOAD_RESTAURANT_DETAILS_SUCCESS_ACTION: 'LOAD_RESTAURANT_DETAILS_SUCCESS_ACTION',
    LOAD_RESTAURANT_DETAILS_FAILURE_ACTION: 'LOAD_RESTAURANT_DETAILS_FAILURE_ACTION',

    ADD_REVIEW_ACTION: 'ADD_REVIEW_ACTION',
    ADD_REVIEW_SUCCESS_ACTION: 'ADD_REVIEW_SUCCESS_ACTION',
    ADD_REVIEW_FAILURE_ACTION: 'ADD_REVIEW_FAILURE_ACTION',

    FILTER_RESTAURANTS_ACTION: 'FILTER_RESTAURANTS_ACTION',

    DELETE_REVIEW_ACTION: 'DELETE_REVIEW_ACTION',
    DELETE_REVIEW_SUCCESS_ACTION: 'DELETE_REVIEW_SUCCESS_ACTION',
    DELETE_REVIEW_FAILURE_ACTION: 'DELETE_REVIEW_FAILURE_ACTION',

    EDIT_REVIEW_ACTION: 'EDIT_REVIEW_ACTION',
    EDIT_REVIEW_SUCCESS_ACTION: 'EDIT_REVIEW_SUCCESS_ACTION',
    EDIT_REVIEW_FAILURE_ACTION: 'EDIT_REVIEW_FAILURE_ACTION',

    SORT_RESTAURANT_REVIEWS_ACTION: 'SORT_RESTAURANT_REVIEWS_ACTION'
};

export {RestaurantsActionsConstants};