const UsersActionsConstants = {
    CHECK_IF_USERNAME_EXISTS_ACTION: 'CHECK_IF_USERNAME_EXISTS_ACTION',
    CHECK_IF_USERNAME_EXISTS_SUCCESS_ACTION: 'CHECK_IF_USERNAME_EXISTS_SUCCESS_ACTION',
    CHECK_IF_USERNAME_EXISTS_FAILURE_ACTION: 'CHECK_IF_USERNAME_EXISTS_FAILURE_ACTION',

    REGISTER_ACTION: 'REGISTER_ACTION',
    REGISTER_SUCCESS_ACTION: 'REGISTER_SUCCESS_ACTION',
    REGISTER_FAILURE_ACTION: 'REGISTER_FAILURE_ACTION',

    LOGIN_ACTION: 'LOGIN_ACTION',
    LOGIN_SUCCESS_ACTION: 'LOGIN_SUCCESS_ACTION',
    LOGIN_FAILURE_ACTION: 'LOGIN_FAILURE_ACTION',

    CHECK_USER_TOKEN_ACTION: 'CHECK_USER_TOKEN_ACTION',
    CHECK_USER_TOKEN_SUCCESS_ACTION: 'CHECK_USER_TOKEN_SUCCESS_ACTION',
    CHECK_USER_TOKEN_FAILURE_ACTION: 'CHECK_USER_TOKEN_FAILURE_ACTION',

    EDIT_PROFILE_ACTION: 'EDIT_PROFILE_ACTION',
    EDIT_PROFILE_SUCCESS_ACTION: 'EDIT_PROFILE_SUCCESS_ACTION',
    EDIT_PROFILE_FAILURE_ACTION: 'EDIT_PROFILE_FAILURE_ACTION',

    LOAD_USER_PROFILE_ACTION: 'LOAD_USER_PROFILE_ACTION',
    LOAD_USER_PROFILE_SUCCESS_ACTION: 'LOAD_USER_PROFILE_SUCCESS_ACTION',
    LOAD_USER_PROFILE_FAILURE_ACTION: 'LOAD_USER_PROFILE_FAILURE_ACTION',

    LOAD_SEARCH_USERNAMES_ACTION: 'LOAD_SEARCH_USERNAMES_ACTION',
    LOAD_SEARCH_USERNAMES_SUCCESS_ACTION: 'LOAD_SEARCH_USERNAMES_SUCCESS_ACTION',
    LOAD_SEARCH_USERNAMES_FAILURE_ACTION: 'LOAD_SEARCH_USERNAMES_SUCCESS_ACTION',
};

export {UsersActionsConstants};